
Vagrant.configure("2") do |config|
#MV3 - WEB SERVER
   config.vm.define :vm3 do |vm3|
	vm3.vm.box = "bento/centos-7.8"
	vm3.vm.network :private_network, ip: "192.168.50.30"
	vm3.vm.hostname = "vm3"
   end

end